#### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Tesla",
    "year": 2019,
    "model": "Model E",
     "lng": 0,
    "lat": 0,
     "mileage": 100,
    "price": 200000
}


### Approve the report
PATCH  http://localhost:3000/reports/2 
Content-Type: application/json

{
    "approved": false
}

