#### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "BMW",
    "year": 2013,
    "model": "5-Series",
     "lng": 0,
    "lat": 0,
     "mileage": 10000,
    "price": 500000
}