#### Create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "year": 2019,
    "model": "V8",
     "lng": 0,
    "lat": 0,
     "mileage": 1000,
    "price": 900000
}

