###Create a new user/signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "kdb@io.xyz",
    "password": "xyzio"
}

### Singin 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"kdb@io.xyz",
    "password":"xyzio"
}

### Get a Signin User Profile
GET http://localhost:3000/auth/myprofile

### SignOut the login user
POST  http://localhost:3000/auth/signout

### Get a User by id
GET http://localhost:3000/auth/4


### Find All users with a given email
GET http://localhost:3000/auth?email=max@io.com

### Delete a user with agiven id
DELETE  http://localhost:3000/auth/4


### Update a user 
PATCH http://localhost:3000/auth/7
Content-Type: application/json

{
    "email":"aaa@bbb.com",
    "password": "bbbbbbbb"
}
